config/routes.rb
Rails.application.routes.draw do
  resources :user_accounts do
    get "sign_out_user", :on => :collection
  end

  devise_for :users

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :user_accounts, :dependent=> :destroy      
end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!  
  after_action :store_location, :except=> :sign_out_user
  

  def store_location
   if current_user
   		$redis.set("user_#{current_user.id}", request.fullpath)
   end 
 end

	def after_sign_in_path_for(resource)
	  $redis.get("user_#{resource.id}") || root_path
	end
  
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
  before_action :set_user_account, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @user_accounts = UserAccount.all
  end

  def sign_out_user
    $redis.del "user_#{current_user.id}"
    sign_out :user
    redirect_to root_path
  end  

  private
    def set_user_account
      @user_account = UserAccount.find(params[:id])
    end

    def user_account_params
      params.require(:user_account).permit(:name, :transaction_date, :transaction_place, :transaction_amount)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
          if request.referrer.nil?
	    redirect_to $redis.get("user_#{current_user.id}")
	  else  
	    redirect_to root_path
	  end
	end
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_accounts_helper.rb
module UserAccountsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AccountManagement" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">AccountManagement</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "Sign out", sign_out_user_user_accounts_path %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "sign in", new_user_session_path %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>

    </div> <!-- /container -->

  </body>
</html>

app/views/user_accounts/index.html.erb
<h1>Listing User accounts</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Transaction date</th>
      <th>Transaction place</th>
      <th>Transaction amount</th>
    </tr>
  </thead>

  <tbody>
    <% @user_accounts.each do |user_account| %>
      <tr>
        <td><%= user_account.name %></td>
        <td><%= user_account.transaction_date %></td>
        <td><%= user_account.transaction_place %></td>
        <td><%= user_account.transaction_amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<div class="row">
	<div class="col-lg-9">
		Welcome user
	</div>
	<div class="col-lg-3 side-links">
      	<div class="well sidebar-nav">            
	        <ul class="nav nav-list">              
	          	<li><%= link_to "User Account Statement", user_accounts_path %></li>
	        </ul>
      	</div><!--/.well -->
    </div><!--/span-->
</div>